/**
 * BYO-Analytics adapters.
 *
 * Lovable forces their built-in dashboard. We let devs use the tool they
 * already love by emitting one small snippet into the project repo.
 *
 * Each adapter exposes:
 *   - kind: stable identifier for the integration row
 *   - label: human-facing name
 *   - fields: config fields the user fills in (project ID, host, etc.)
 *   - filePath: where the snippet lives in the project
 *   - buildSnippet(config): returns the file contents
 *
 * Snippets are intentionally framework-agnostic head-snippets where possible
 * (work in Next.js, Remix, TanStack Start, Vite + React Router). The user
 * imports them in their root layout.
 */

export type AnalyticsKind = 'posthog' | 'plausible' | 'umami' | 'ga4'

export interface AdapterField {
  key:         string
  label:       string
  placeholder?: string
  hint?:        string
  required?:    boolean
}

export interface AnalyticsAdapter {
  kind:        AnalyticsKind
  label:       string
  description: string
  homepage:    string
  pricing:     string                          // short marketing line
  fields:      AdapterField[]
  filePath:    string                          // where to write the snippet
  buildSnippet: (config: Record<string, string>) => string
}

// ─── PostHog ────────────────────────────────────────────────────────────────

const posthog: AnalyticsAdapter = {
  kind: 'posthog',
  label: 'PostHog',
  description: 'Product analytics + session replay + feature flags. Self-host or cloud.',
  homepage: 'https://posthog.com',
  pricing: 'Free up to 1M events/mo',
  fields: [
    { key: 'project_key', label: 'Project API Key', placeholder: 'phc_…', required: true },
    { key: 'host',        label: 'Host', placeholder: 'https://us.i.posthog.com', hint: 'Use eu.i.posthog.com for EU region or your self-hosted URL' },
  ],
  filePath: 'lib/analytics/posthog.ts',
  buildSnippet: (cfg) => `// Generated by SpringBloom — BYO Analytics (PostHog)
// Import this once in your root layout, e.g. app/layout.tsx:
//   import '@/lib/analytics/posthog'
// In Next.js app router, place the import inside a client component.

import posthog from 'posthog-js'

const KEY  = process.env.NEXT_PUBLIC_POSTHOG_KEY  ?? ${JSON.stringify(cfg.project_key ?? '')}
const HOST = process.env.NEXT_PUBLIC_POSTHOG_HOST ?? ${JSON.stringify(cfg.host || 'https://us.i.posthog.com')}

if (typeof window !== 'undefined' && KEY) {
  posthog.init(KEY, {
    api_host: HOST,
    capture_pageview: true,
    capture_pageleave: true,
    persistence: 'localStorage+cookie',
  })
}

export { posthog }
`,
}

// ─── Plausible ──────────────────────────────────────────────────────────────

const plausible: AnalyticsAdapter = {
  kind: 'plausible',
  label: 'Plausible',
  description: 'Privacy-friendly, no cookies, GDPR/CCPA compliant. Lightweight script.',
  homepage: 'https://plausible.io',
  pricing: 'Paid only — from $9/mo',
  fields: [
    { key: 'domain', label: 'Site domain', placeholder: 'yourdomain.com', required: true, hint: 'Without https://' },
    { key: 'host',   label: 'Custom host (optional)', placeholder: 'https://plausible.io', hint: 'Set if self-hosting Plausible' },
  ],
  filePath: 'components/analytics/PlausibleScript.tsx',
  buildSnippet: (cfg) => `// Generated by SpringBloom — BYO Analytics (Plausible)
// Drop into your root layout:
//   <head>...<PlausibleScript /></head>

import Script from 'next/script'

const DOMAIN = ${JSON.stringify(cfg.domain ?? 'yourdomain.com')}
const HOST   = ${JSON.stringify(cfg.host || 'https://plausible.io')}

export function PlausibleScript() {
  return (
    <Script
      defer
      data-domain={DOMAIN}
      src={\`\${HOST}/js/script.js\`}
      strategy="afterInteractive"
    />
  )
}
`,
}

// ─── Umami ──────────────────────────────────────────────────────────────────

const umami: AnalyticsAdapter = {
  kind: 'umami',
  label: 'Umami',
  description: 'Open-source, self-hostable, cookieless. Plausible alternative.',
  homepage: 'https://umami.is',
  pricing: 'Free if self-hosted · $9/mo cloud',
  fields: [
    { key: 'website_id', label: 'Website ID',    placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', required: true },
    { key: 'host',       label: 'Umami host',    placeholder: 'https://cloud.umami.is', required: true, hint: 'Your Umami instance URL' },
  ],
  filePath: 'components/analytics/UmamiScript.tsx',
  buildSnippet: (cfg) => `// Generated by SpringBloom — BYO Analytics (Umami)

import Script from 'next/script'

const WEBSITE_ID = ${JSON.stringify(cfg.website_id ?? '')}
const HOST       = ${JSON.stringify(cfg.host ?? '')}

export function UmamiScript() {
  return (
    <Script
      defer
      data-website-id={WEBSITE_ID}
      src={\`\${HOST}/script.js\`}
      strategy="afterInteractive"
    />
  )
}
`,
}

// ─── Google Analytics 4 ─────────────────────────────────────────────────────

const ga4: AnalyticsAdapter = {
  kind: 'ga4',
  label: 'Google Analytics 4',
  description: 'The default for free analytics. Cookie consent often required.',
  homepage: 'https://analytics.google.com',
  pricing: 'Free up to 10M events/mo',
  fields: [
    { key: 'measurement_id', label: 'Measurement ID', placeholder: 'G-XXXXXXXXXX', required: true },
  ],
  filePath: 'components/analytics/GAScript.tsx',
  buildSnippet: (cfg) => `// Generated by SpringBloom — BYO Analytics (Google Analytics 4)
// NOTE: most jurisdictions require a cookie consent banner before loading GA.
//       Gate this script on consent.

import Script from 'next/script'

const MEASUREMENT_ID = ${JSON.stringify(cfg.measurement_id ?? '')}

export function GAScript() {
  if (!MEASUREMENT_ID) return null
  return (
    <>
      <Script
        src={\`https://www.googletagmanager.com/gtag/js?id=\${MEASUREMENT_ID}\`}
        strategy="afterInteractive"
      />
      <Script id="ga4-init" strategy="afterInteractive">{\`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '\${MEASUREMENT_ID}', { send_page_view: true });
      \`}</Script>
    </>
  )
}
`,
}

// ─── Registry ───────────────────────────────────────────────────────────────

export const ANALYTICS_ADAPTERS: Record<AnalyticsKind, AnalyticsAdapter> = {
  posthog, plausible, umami, ga4,
}

export const ANALYTICS_KINDS: AnalyticsKind[] = ['posthog', 'plausible', 'umami', 'ga4']
