/**
 * B2: Resend Email Scaffold.
 *
 * Drops React Email templates + a typed sendEmail() helper into the user's
 * repo. Lovable hides the template layer; devs want React Email components
 * they can edit, version, and preview locally.
 *
 * Generated files:
 *   - lib/emails/send.ts            — typed sendEmail() helper, discriminates on template
 *   - lib/emails/templates/welcome.tsx
 *   - lib/emails/templates/password-reset.tsx
 *   - lib/emails/templates/magic-link.tsx
 *   - lib/emails/templates/receipt.tsx
 *   - lib/emails/preview.tsx        — dev-only preview route mountable at /email-preview
 */

export interface EmailScaffoldConfig {
  fromAddress?:   string             // e.g. 'noreply@yourdomain.com'
  fromName?:      string             // e.g. 'Acme'
  productName?:   string             // shown inside templates
  brandColor?:    string             // hex
  includeReceipt?: boolean
}

export interface GeneratedFile { path: string; content: string; byteSize: number }

export function generateEmailScaffold(cfg: EmailScaffoldConfig = {}): GeneratedFile[] {
  const product = cfg.productName ?? 'Your App'
  const from    = cfg.fromAddress ?? 'noreply@yourdomain.com'
  const fromNm  = cfg.fromName ?? product
  const color   = cfg.brandColor ?? '#7c3aed'

  const files: GeneratedFile[] = [
    mk('lib/emails/send.ts',                       buildSendHelper(from, fromNm)),
    mk('lib/emails/templates/welcome.tsx',         buildWelcome(product, color)),
    mk('lib/emails/templates/password-reset.tsx',  buildPasswordReset(product, color)),
    mk('lib/emails/templates/magic-link.tsx',      buildMagicLink(product, color)),
    mk('lib/emails/preview.tsx',                   buildPreviewIndex(cfg.includeReceipt !== false)),
  ]
  if (cfg.includeReceipt !== false) {
    files.push(mk('lib/emails/templates/receipt.tsx', buildReceipt(product, color)))
  }
  return files
}

function mk(path: string, content: string): GeneratedFile {
  return { path, content, byteSize: Buffer.byteLength(content, 'utf8') }
}

// ─── lib/emails/send.ts ─────────────────────────────────────────────────────

function buildSendHelper(from: string, fromName: string): string {
  return `// Generated by SpringBloom — typed Resend send() helper.
//
// SERVER ONLY. Resend's API key must never reach the browser.
// Each template is a discriminated union so missing variables fail at compile time.

import { Resend } from 'resend'
import { render } from '@react-email/render'
import { Welcome }       from './templates/welcome'
import { PasswordReset } from './templates/password-reset'
import { MagicLink }     from './templates/magic-link'
import { Receipt }       from './templates/receipt'

const resend = new Resend(process.env.RESEND_API_KEY)
const DEFAULT_FROM = '${fromName} <${from}>'

export type EmailPayload =
  | { template: 'welcome';        to: string; props: { name: string } }
  | { template: 'password-reset'; to: string; props: { resetUrl: string; name?: string } }
  | { template: 'magic-link';     to: string; props: { signInUrl: string; expiresInMinutes?: number } }
  | { template: 'receipt';        to: string; props: { name: string; amount: number; currency: string; itemDescription: string; invoiceUrl?: string } }

export async function sendEmail(p: EmailPayload): Promise<{ id: string }> {
  const { html, subject } = await renderTemplate(p)
  const res = await resend.emails.send({
    from: DEFAULT_FROM,
    to:   p.to,
    subject,
    html,
  })
  if (res.error) throw new Error(\`Resend send failed: \${res.error.message}\`)
  return { id: res.data?.id ?? 'unknown' }
}

async function renderTemplate(p: EmailPayload): Promise<{ html: string; subject: string }> {
  switch (p.template) {
    case 'welcome':
      return { subject: 'Welcome 👋', html: await render(Welcome(p.props)) }
    case 'password-reset':
      return { subject: 'Reset your password', html: await render(PasswordReset(p.props)) }
    case 'magic-link':
      return { subject: 'Your sign-in link', html: await render(MagicLink(p.props)) }
    case 'receipt':
      return { subject: \`Receipt — \${p.props.itemDescription}\`, html: await render(Receipt(p.props)) }
  }
}
`
}

// ─── Templates ──────────────────────────────────────────────────────────────

function buildWelcome(product: string, color: string): string {
  return `// Generated by SpringBloom — React Email template.

import { Body, Button, Container, Head, Heading, Html, Link, Preview, Section, Text } from '@react-email/components'

const BRAND = '${color}'

export interface WelcomeProps { name: string }

export function Welcome({ name }: WelcomeProps) {
  return (
    <Html>
      <Head />
      <Preview>Welcome to ${product} — let’s get you started.</Preview>
      <Body style={{ background: '#f6f8fb', fontFamily: 'system-ui, sans-serif', padding: '32px 0' }}>
        <Container style={{ background: '#fff', borderRadius: 12, padding: 32, maxWidth: 520, margin: '0 auto' }}>
          <Heading style={{ color: BRAND, marginTop: 0 }}>Welcome, {name} 👋</Heading>
          <Text>Thanks for signing up for ${product}. You're in.</Text>
          <Section style={{ textAlign: 'center', margin: '24px 0' }}>
            <Button href="https://example.com/dashboard" style={{ background: BRAND, color: '#fff', padding: '12px 20px', borderRadius: 6, textDecoration: 'none' }}>
              Open your dashboard
            </Button>
          </Section>
          <Text style={{ fontSize: 13, color: '#666' }}>If you have any questions just reply to this email — we read every message.</Text>
          <Section style={{ borderTop: '1px solid #eee', marginTop: 24, paddingTop: 16 }}>
            <Text style={{ fontSize: 11, color: '#888', margin: 0 }}>${product} · <Link href="https://example.com">example.com</Link></Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}
`
}

function buildPasswordReset(product: string, color: string): string {
  return `// Generated by SpringBloom — React Email template.

import { Body, Button, Container, Head, Heading, Html, Link, Preview, Section, Text } from '@react-email/components'

const BRAND = '${color}'

export interface PasswordResetProps {
  resetUrl: string
  name?: string
}

export function PasswordReset({ resetUrl, name }: PasswordResetProps) {
  return (
    <Html>
      <Head />
      <Preview>Reset your ${product} password</Preview>
      <Body style={{ background: '#f6f8fb', fontFamily: 'system-ui, sans-serif', padding: '32px 0' }}>
        <Container style={{ background: '#fff', borderRadius: 12, padding: 32, maxWidth: 520, margin: '0 auto' }}>
          <Heading style={{ color: BRAND, marginTop: 0 }}>Reset your password</Heading>
          <Text>{name ? \`Hi \${name},\` : 'Hi,'} someone (hopefully you) asked to reset your ${product} password.</Text>
          <Section style={{ textAlign: 'center', margin: '24px 0' }}>
            <Button href={resetUrl} style={{ background: BRAND, color: '#fff', padding: '12px 20px', borderRadius: 6, textDecoration: 'none' }}>
              Reset password
            </Button>
          </Section>
          <Text style={{ fontSize: 13, color: '#666' }}>This link expires in 1 hour. If you didn't request a reset, ignore this email — your password stays the same.</Text>
          <Section style={{ borderTop: '1px solid #eee', marginTop: 24, paddingTop: 16 }}>
            <Text style={{ fontSize: 11, color: '#888', margin: 0 }}>${product} · <Link href="https://example.com">example.com</Link></Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}
`
}

function buildMagicLink(product: string, color: string): string {
  return `// Generated by SpringBloom — React Email template.

import { Body, Button, Container, Head, Heading, Html, Link, Preview, Section, Text } from '@react-email/components'

const BRAND = '${color}'

export interface MagicLinkProps {
  signInUrl: string
  expiresInMinutes?: number
}

export function MagicLink({ signInUrl, expiresInMinutes = 15 }: MagicLinkProps) {
  return (
    <Html>
      <Head />
      <Preview>Your ${product} sign-in link</Preview>
      <Body style={{ background: '#f6f8fb', fontFamily: 'system-ui, sans-serif', padding: '32px 0' }}>
        <Container style={{ background: '#fff', borderRadius: 12, padding: 32, maxWidth: 520, margin: '0 auto' }}>
          <Heading style={{ color: BRAND, marginTop: 0 }}>Sign in to ${product}</Heading>
          <Text>Click below to sign in. This link expires in {expiresInMinutes} minutes.</Text>
          <Section style={{ textAlign: 'center', margin: '24px 0' }}>
            <Button href={signInUrl} style={{ background: BRAND, color: '#fff', padding: '12px 20px', borderRadius: 6, textDecoration: 'none' }}>
              Sign in
            </Button>
          </Section>
          <Text style={{ fontSize: 13, color: '#666' }}>If you didn’t try to sign in, you can safely ignore this email.</Text>
          <Section style={{ borderTop: '1px solid #eee', marginTop: 24, paddingTop: 16 }}>
            <Text style={{ fontSize: 11, color: '#888', margin: 0 }}>${product} · <Link href="https://example.com">example.com</Link></Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}
`
}

function buildReceipt(product: string, color: string): string {
  return `// Generated by SpringBloom — React Email template (transactional receipt).

import { Body, Button, Container, Head, Heading, Hr, Html, Link, Preview, Row, Column, Section, Text } from '@react-email/components'

const BRAND = '${color}'

export interface ReceiptProps {
  name: string
  amount: number
  currency: string
  itemDescription: string
  invoiceUrl?: string
}

export function Receipt({ name, amount, currency, itemDescription, invoiceUrl }: ReceiptProps) {
  const display = new Intl.NumberFormat('en-US', { style: 'currency', currency: currency.toUpperCase() }).format(amount / 100)
  return (
    <Html>
      <Head />
      <Preview>Your ${product} receipt</Preview>
      <Body style={{ background: '#f6f8fb', fontFamily: 'system-ui, sans-serif', padding: '32px 0' }}>
        <Container style={{ background: '#fff', borderRadius: 12, padding: 32, maxWidth: 520, margin: '0 auto' }}>
          <Heading style={{ color: BRAND, marginTop: 0 }}>Receipt</Heading>
          <Text>Thanks {name}, here are your payment details.</Text>

          <Hr style={{ borderColor: '#eee' }} />
          <Row><Column style={{ color: '#666' }}>Item</Column><Column style={{ textAlign: 'right' }}>{itemDescription}</Column></Row>
          <Row><Column style={{ color: '#666' }}>Amount</Column><Column style={{ textAlign: 'right', fontWeight: 600 }}>{display}</Column></Row>
          <Hr style={{ borderColor: '#eee' }} />

          {invoiceUrl && (
            <Section style={{ textAlign: 'center', margin: '24px 0' }}>
              <Button href={invoiceUrl} style={{ background: BRAND, color: '#fff', padding: '12px 20px', borderRadius: 6, textDecoration: 'none' }}>
                View invoice
              </Button>
            </Section>
          )}

          <Section style={{ borderTop: '1px solid #eee', marginTop: 24, paddingTop: 16 }}>
            <Text style={{ fontSize: 11, color: '#888', margin: 0 }}>${product} · <Link href="https://example.com">example.com</Link></Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}
`
}

function buildPreviewIndex(includeReceipt: boolean): string {
  return `// Generated by SpringBloom — local-only email preview index.
//
// Mount this at a dev-only route, e.g. app/email-preview/page.tsx:
//
//   import { PreviewIndex } from '@/lib/emails/preview'
//   export default PreviewIndex
//
// Then visit /email-preview during development to inspect each template.

import { render } from '@react-email/render'
import { Welcome }       from './templates/welcome'
import { PasswordReset } from './templates/password-reset'
import { MagicLink }     from './templates/magic-link'
${includeReceipt ? "import { Receipt }       from './templates/receipt'" : ''}

const SAMPLES = [
  { name: 'welcome',        html: await render(Welcome({ name: 'Sam' })) },
  { name: 'password-reset', html: await render(PasswordReset({ resetUrl: 'https://example.com/reset?token=demo', name: 'Sam' })) },
  { name: 'magic-link',     html: await render(MagicLink({ signInUrl: 'https://example.com/auth?token=demo', expiresInMinutes: 15 })) },
${includeReceipt ? "  { name: 'receipt',        html: await render(Receipt({ name: 'Sam', amount: 2900, currency: 'usd', itemDescription: 'Pro plan · monthly' })) }," : ''}
]

export default function PreviewIndex() {
  return (
    <div style={{ padding: 32, background: '#f0f2f5', minHeight: '100vh' }}>
      <h1 style={{ marginTop: 0 }}>Email Previews</h1>
      <p style={{ color: '#666' }}>Dev only. Each template rendered with sample props.</p>
      <div style={{ display: 'grid', gap: 24, gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))', marginTop: 24 }}>
        {SAMPLES.map((s) => (
          <div key={s.name} style={{ background: '#fff', borderRadius: 8, padding: 16 }}>
            <h3 style={{ marginTop: 0, fontFamily: 'system-ui' }}>{s.name}</h3>
            <iframe srcDoc={s.html} style={{ width: '100%', height: 600, border: '1px solid #ddd', borderRadius: 4 }} />
          </div>
        ))}
      </div>
    </div>
  )
}
`
}
