import { LegalPage } from "@/components/legal/LegalPage"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — SpringBloom",
  description: "SpringBloom terms of service governing your use of the platform.",
}

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle="Please read these terms carefully before using SpringBloom. By accessing or using the platform you agree to be bound by them."
      effectiveDate="May 20, 2026"
    >
      <div className="notice-box">
        <strong>For lawyer review.</strong> This document was drafted based on industry-standard SaaS terms
        and is pending legal review before final publication. Placeholders marked [BRACKET] require confirmation.
      </div>

      <h2>1. Who We Are</h2>
      <p>
        SpringBloom (&ldquo;SpringBloom,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) is operated
        by SpringBloom, Inc. [ENTITY JURISDICTION AND REGISTRATION NUMBER TO BE CONFIRMED]. Our registered
        address is [ADDRESS]. You can contact us at <a href="mailto:legal@springbloom.app">legal@springbloom.app</a>.
      </p>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the SpringBloom website,
        platform, APIs, and all related services (collectively, the &ldquo;Services&rdquo;). They form a binding
        legal agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and SpringBloom.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old to use the Services. By using the Services you represent that you meet
        this requirement and have the legal capacity to enter into a binding contract. If you are using the
        Services on behalf of a business or organization, you represent that you have the authority to bind that
        entity to these Terms.
      </p>
      <p>
        You may not use the Services if you are located in, or are a national or resident of, any country subject
        to applicable trade sanctions or export control laws, including countries on the U.S. Office of Foreign
        Assets Control (OFAC) sanctions list.
      </p>

      <h2>3. Accounts</h2>
      <p>
        You must create an account to use most features of the Services. You are responsible for maintaining the
        security of your account credentials and for all activity that occurs under your account. Notify us
        immediately at <a href="mailto:security@springbloom.app">security@springbloom.app</a> if you suspect
        any unauthorized access.
      </p>
      <p>
        You may not share your account, create accounts by automated means, or create accounts for the purpose
        of circumventing restrictions.
      </p>

      <h2>4. License to Use</h2>
      <p>
        Subject to your compliance with these Terms, SpringBloom grants you a limited, non-exclusive,
        non-transferable, non-sublicensable, revocable license to access and use the Services for your own
        personal or internal business purposes.
      </p>
      <p>You may not:</p>
      <ul>
        <li>Resell, sublicense, or otherwise make the Services available to third parties as a standalone product</li>
        <li>Reverse engineer, decompile, or attempt to extract the source code of the Services or any AI models</li>
        <li>Scrape, crawl, or use automated tools to extract data from the Services beyond what is permitted by our API</li>
        <li>Use the Services to train, fine-tune, or build competing AI models</li>
        <li>Remove, alter, or obscure any proprietary notices on the Services</li>
        <li>Use the Services in any manner that violates applicable law or these Terms</li>
      </ul>

      <h2>5. AI-Generated Output</h2>
      <h3>5.1 Ownership</h3>
      <p>
        Subject to your compliance with these Terms and full payment of applicable fees, you own the application
        code and content generated by the Services in response to your prompts (&ldquo;AI Output&rdquo;), to the
        extent permitted by applicable law and the terms of the underlying AI model providers.
      </p>
      <h3>5.2 No Warranty on Output</h3>
      <p>
        AI Output is generated by large language models and may contain errors, inaccuracies, outdated
        information, or security vulnerabilities. <strong>Do not use AI Output in production without independent
        technical review.</strong> Do not rely on AI Output for medical, legal, financial, safety-critical, or
        other high-stakes purposes without appropriate professional review and safeguards.
      </p>
      <h3>5.3 No Training on Your Data</h3>
      <p>
        SpringBloom does not use your prompts, project content, or generated AI Output to train or fine-tune
        AI models. We may use aggregated, anonymized, non-identifiable usage statistics (such as prompt length
        distributions or feature usage rates) to improve platform performance. See our
        <a href="/privacy"> Privacy Policy</a> for full details.
      </p>
      <h3>5.4 License Grant for Service Operation</h3>
      <p>
        You grant SpringBloom a limited, worldwide, royalty-free license to process, store, transmit, and display
        your prompts, project files, and AI Output solely as necessary to provide the Services to you. This
        license does not include the right to use your data for AI model training.
      </p>

      <h2>6. Credits and Billing</h2>
      <h3>6.1 Credits</h3>
      <p>
        The Services use a credit-based system. Credits are consumed when you use AI generation features.
        You can purchase credits or receive them through your subscription plan. Credit balances are displayed
        in your account dashboard. SpringBloom shows an estimate before each generation, holds the estimated
        amount during generation, and deducts the actual amount on completion.
      </p>
      <h3>6.2 Subscriptions</h3>
      <p>
        Subscription plans are billed in advance on a monthly or annual cycle. Subscriptions automatically
        renew unless cancelled before the renewal date. Monthly credit allocations are provided at the start
        of each billing period and do not roll over to the following period, except as described in the plan
        details.
      </p>
      <h3>6.3 Non-Refundable</h3>
      <p>
        All credit purchases and subscription fees are non-refundable except where required by applicable law
        or as described in our <a href="/refund">Refund Policy</a>. Credits have no monetary value and cannot
        be transferred, sold, or exchanged.
      </p>
      <h3>6.4 Price Changes</h3>
      <p>
        SpringBloom may change its pricing with at least 30 days&rsquo; notice via email or in-product
        notification. Continued use of the Services after the price change takes effect constitutes acceptance
        of the new pricing.
      </p>

      <h2>7. Subdomains and Deployed Apps</h2>
      <p>
        Apps you publish through the Services may be accessible at a SpringBloom subdomain
        (e.g., <code>yourapp.springbloom.app</code>). SpringBloom retains ownership of the domain. We may
        reclaim or redirect a subdomain with 7 days&rsquo; advance notice, or immediately without notice if
        the subdomain is used to distribute illegal content, malware, or violates these Terms.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        SpringBloom and its licensors retain all intellectual property rights in the Services, platform
        software, AI models, documentation, trademarks, and all related materials (&ldquo;SpringBloom
        Materials&rdquo;). Nothing in these Terms transfers any SpringBloom IP to you.
      </p>
      <p>
        If you submit feedback, suggestions, or ideas about the Services
        (&ldquo;Feedback&rdquo;), you grant SpringBloom an irrevocable, worldwide, royalty-free license to
        use that Feedback for any purpose without compensation to you.
      </p>

      <h2>9. Prohibited Uses</h2>
      <p>You agree not to use the Services to:</p>
      <ul>
        <li>Generate, host, or distribute illegal content, including child sexual abuse material (CSAM)</li>
        <li>Harass, threaten, defame, or discriminate against any individual or group</li>
        <li>Create or distribute malware, spyware, ransomware, or other malicious code</li>
        <li>Conduct cryptocurrency mining using platform resources</li>
        <li>Circumvent rate limits, credit systems, or billing mechanisms</li>
        <li>Violate the intellectual property rights of any third party</li>
        <li>Impersonate SpringBloom, our employees, or other users</li>
        <li>Misrepresent AI-generated content as being authored by a human in contexts where this is deceptive or harmful</li>
        <li>Use the Services in violation of any applicable local, national, or international law or regulation</li>
      </ul>

      <h2>10. Termination and Suspension</h2>
      <p>
        SpringBloom may suspend or terminate your account immediately and without prior notice if we determine,
        in our sole discretion, that you have violated these Terms. Upon termination for cause, any unused credits
        are forfeited and are not refundable.
      </p>
      <p>
        You may cancel your account at any time from your account settings. If you cancel a subscription,
        you retain access to paid features until the end of the current billing period. Credits purchased
        separately are forfeited on account deletion.
      </p>
      <p>
        We may discontinue the Services or any feature thereof with at least 30 days&rsquo; notice.
      </p>

      <h2>11. DMCA and Copyright</h2>
      <p>
        SpringBloom respects intellectual property rights. If you believe content on the Services infringes
        your copyright, please send a DMCA notice to <a href="mailto:dmca@springbloom.app">dmca@springbloom.app</a> with:
      </p>
      <ul>
        <li>Identification of the copyrighted work claimed to be infringed</li>
        <li>Identification of the infringing material and its location</li>
        <li>Your contact information</li>
        <li>A statement of good-faith belief that the use is not authorized</li>
        <li>A statement, under penalty of perjury, that the information is accurate and you are the rights owner or authorized agent</li>
        <li>Your physical or electronic signature</li>
      </ul>
      <p>
        We will respond to valid DMCA notices and may terminate accounts of repeat infringers.
      </p>

      <h2>12. Disclaimers</h2>
      <p>
        THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTY OF ANY
        KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SPRINGBLOOM EXPRESSLY DISCLAIMS ALL WARRANTIES,
        WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR
        A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
      </p>
      <p>
        SPRINGBLOOM DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT
        ANY DEFECTS WILL BE CORRECTED. YOU USE THE SERVICES AT YOUR OWN RISK.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SPRINGBLOOM&rsquo;S TOTAL CUMULATIVE LIABILITY TO
        YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE GREATER
        OF (A) THE AMOUNT YOU PAID TO SPRINGBLOOM IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR
        (B) USD $50.
      </p>
      <p>
        IN NO EVENT SHALL SPRINGBLOOM BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE,
        OR EXEMPLARY DAMAGES, INCLUDING LOSS OF PROFITS, DATA, BUSINESS, OR GOODWILL, EVEN IF SPRINGBLOOM HAS
        BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
      </p>
      <p>
        Some jurisdictions do not allow exclusion or limitation of certain warranties or damages. The above
        limitations apply to the fullest extent permitted by applicable law in your jurisdiction.
      </p>

      <h2>14. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless SpringBloom, its officers, directors, employees,
        and agents from any claims, damages, losses, liabilities, and expenses (including reasonable legal fees)
        arising out of: (a) your use of the Services; (b) your violation of these Terms; (c) your violation of
        any third-party right; or (d) content you submit, generate, or publish through the Services.
      </p>

      <h2>15. Governing Law and Disputes</h2>
      <p>
        These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict
        of law principles. [TO BE CONFIRMED BY COUNSEL]
      </p>
      <p>
        Any dispute arising out of or relating to these Terms or the Services shall be resolved by binding
        individual arbitration administered by [ARBITRATION BODY — e.g., AAA] under its then-current rules.
        YOU WAIVE ANY RIGHT TO A JURY TRIAL OR TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE
        ARBITRATION. [TO BE CONFIRMED BY COUNSEL]
      </p>

      <h2>16. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes via email or an
        in-product notice at least 14 days before the changes take effect. Continued use of the Services after
        the effective date constitutes acceptance of the updated Terms.
      </p>

      <h2>17. General</h2>
      <p>
        These Terms, together with our Privacy Policy, Acceptable Use Policy, and any plan-specific agreements,
        constitute the entire agreement between you and SpringBloom. If any provision is found unenforceable,
        the remaining provisions remain in effect. SpringBloom&rsquo;s failure to enforce any right or provision
        is not a waiver. You may not assign these Terms; SpringBloom may assign them in connection with a merger,
        acquisition, or sale of assets.
      </p>
      <p>
        Questions? Email us at <a href="mailto:legal@springbloom.app">legal@springbloom.app</a>.
      </p>
    </LegalPage>
  )
}
