import type { Metadata } from "next";
import { ShieldCheck, Lock, Eye, ServerCrash, KeyRound, FileSearch, Globe, CheckCircle2 } from "lucide-react";
import { Navbar } from "@/components/marketing/Navbar";
import { Footer } from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Security — SpringBloom",
  description:
    "SpringBloom is built with security as a first-class concern — RLS, secrets scanning, CSP headers, audit logs, and SOC 2-aligned practices baked into every generated app.",
  openGraph: {
    title: "Security — SpringBloom",
    description: "How SpringBloom keeps your apps and data secure — by default, not as an afterthought.",
    type: "website",
  },
};

const PILLARS = [
  {
    icon: Lock,
    title: "Row-Level Security by default",
    body: "Every Supabase project generated by SpringBloom includes RLS policies. The agent checks for missing or overly permissive policies before accepting generated code.",
  },
  {
    icon: KeyRound,
    title: "Secrets scanning",
    body: "AI-generated code is scanned for hardcoded API keys, tokens, and credentials before they reach your preview or repository. Violations are flagged and blocked.",
  },
  {
    icon: ShieldCheck,
    title: "Security headers on every app",
    body: "Every SpringBloom deployment ships with Strict-Transport-Security, Content-Security-Policy, Cross-Origin-Opener-Policy, and X-Frame-Options headers pre-configured.",
  },
  {
    icon: FileSearch,
    title: "Dependency auditing",
    body: "New npm packages added by the agent are checked against known CVE databases. High-severity vulnerabilities surface as warnings before you approve the change.",
  },
  {
    icon: Eye,
    title: "Code review built in",
    body: "Every meaningful generated diff is reviewed for auth patterns, input validation, CORS configuration, and SQL injection vectors — automatically, before you see it.",
  },
  {
    icon: Globe,
    title: "Isolated preview machines",
    body: "Each project runs in an isolated Fly.io machine. Projects cannot communicate with each other, and machines auto-suspend when idle to minimize attack surface.",
  },
  {
    icon: ServerCrash,
    title: "Credit-gated generation",
    body: "Generation requires pre-authorized credits. Prompt injection and runaway agent loops are bounded by credit limits, preventing uncontrolled cost or output escalation.",
  },
  {
    icon: CheckCircle2,
    title: "Content safety filter",
    body: "All user prompts are screened against a safety ruleset before reaching the AI. Blocked requests are logged, never billed, and the user is notified immediately.",
  },
];

const PRACTICES = [
  "Service-role keys never exposed to client bundles",
  "All Supabase queries go through RLS-enforced policies",
  "User-uploaded files stored in per-user isolated storage buckets",
  "Rate limiting on all AI endpoints (Upstash Redis)",
  "Fork and file-write operations path-sanitized to prevent directory traversal",
  "OAuth state validation on all Stripe Connect callbacks",
  "Advisory-lock RPC for atomic credit holds (no double-spend)",
  "Admin routes protected by is_admin profile check + middleware guard",
];

export default function SecurityPage() {
  return (
    <main className="page-shell">
      <Navbar />

      {/* Hero */}
      <section className="hero">
        <div className="container text-center">
          <div className="mx-auto mb-5 flex w-fit items-center gap-2 rounded-full border border-purple-500/30 bg-purple-950/40 px-4 py-1.5 text-sm font-semibold text-purple-300">
            <ShieldCheck size={15} /> Security
          </div>
          <h1 className="text-5xl md:text-6xl">Security is not<br />a checkbox.</h1>
          <p className="hero-copy mx-auto max-w-2xl">
            SpringBloom bakes security into every layer — generated code, deployed infrastructure,
            and platform operations. Here's exactly what we do and why.
          </p>
        </div>
      </section>

      {/* 8 pillars */}
      <section className="section">
        <div className="container">
          <h2 className="text-center">Eight security pillars</h2>
          <p className="section-lede text-center">
            Every generated app and every platform operation is covered.
          </p>
          <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {PILLARS.map(({ icon: Icon, title, body }) => (
              <article className="card feature-card" key={title}>
                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-purple-950/60 text-purple-400">
                  <Icon size={20} />
                </div>
                <h3 className="text-base leading-snug">{title}</h3>
                <p className="mt-2 text-sm text-slate-400">{body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Practices list */}
      <section className="section bg-zinc-950">
        <div className="container">
          <div className="mx-auto max-w-3xl">
            <h2 className="text-center">Platform practices</h2>
            <p className="section-lede text-center">
              These aren't aspirational goals — they're already running in production.
            </p>
            <ul className="mt-10 space-y-3">
              {PRACTICES.map((item) => (
                <li className="flex items-start gap-3" key={item}>
                  <CheckCircle2 className="mt-0.5 shrink-0 text-green-400" size={18} />
                  <span className="text-slate-300">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Responsible disclosure */}
      <section className="section border-t border-zinc-800/60">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2>Found a vulnerability?</h2>
            <p className="section-lede">
              We take security reports seriously. If you've found a potential issue, please email us
              directly — we respond within 24 hours and credit researchers who report responsibly.
            </p>
            <a
              className="inline-flex items-center gap-2 rounded-lg border border-purple-600 px-6 py-3 font-semibold text-purple-300 transition-colors hover:bg-purple-950/40"
              href="mailto:security@springbloom.dev"
            >
              security@springbloom.dev
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
