import type { Metadata } from "next";
import { ShieldCheck, Lock, KeyRound, Eye, FileSearch, Globe, CheckCircle2, ArrowRight } from "lucide-react";
import { Navbar } from "@/components/marketing/Navbar";
import { Footer } from "@/components/shared/Footer";
import { AnimateIn } from "@/components/shared/AnimateIn";

export const metadata: Metadata = {
  title: "Security — SpringBloom",
  description:
    "SpringBloom is built with security as a first-class concern — RLS, secrets scanning, CSP headers, audit logs, and SOC 2-aligned practices baked into every generated app.",
};

// ── Pillar slides ─────────────────────────────────────────────────────────────

const SLIDES = [
  {
    icon: Lock,
    eyebrow: "Database security",
    title: "Row-Level Security by default.",
    body: "Every Supabase project generated by SpringBloom ships with RLS policies in place. The agent refuses to finalise code if policies are overly permissive or missing entirely.",
    stat: "100%",
    statLabel: "of generated projects have RLS enabled",
  },
  {
    icon: KeyRound,
    eyebrow: "Secrets detection",
    title: "No hardcoded credentials — ever.",
    body: "Generated code is scanned for API keys, tokens, and credentials before it reaches your preview or repository. Violations are flagged, blocked, and never committed.",
    stat: "0",
    statLabel: "secrets shipped to production",
  },
  {
    icon: ShieldCheck,
    eyebrow: "HTTP security",
    title: "Headers that protect every page.",
    body: "Strict-Transport-Security, Content-Security-Policy, Cross-Origin-Opener-Policy, and X-Frame-Options are pre-configured on every SpringBloom deployment out of the box.",
    stat: "6",
    statLabel: "security headers enabled by default",
  },
  {
    icon: FileSearch,
    eyebrow: "Dependency health",
    title: "CVE checks before you approve.",
    body: "Every new package the agent wants to add is checked against known vulnerability databases. High-severity issues surface as warnings before the change is accepted.",
    stat: "< 1s",
    statLabel: "average scan time per dependency",
  },
  {
    icon: Eye,
    eyebrow: "Content safety",
    title: "Every prompt is screened.",
    body: "User prompts are checked against a safety ruleset before reaching any AI model. Blocked requests are never billed, are logged for audit, and the user is notified immediately.",
    stat: "0 credits",
    statLabel: "charged on blocked requests",
  },
  {
    icon: Globe,
    eyebrow: "Infrastructure isolation",
    title: "Every project runs in its own machine.",
    body: "Projects live in isolated Fly.io machines. They cannot communicate with each other, auto-suspend when idle, and are torn down cleanly when a project is deleted.",
    stat: "100%",
    statLabel: "project isolation at the infrastructure level",
  },
] as const;

// ── Platform practices ────────────────────────────────────────────────────────

const PRACTICES = [
  "Service-role keys never exposed to client bundles",
  "All Supabase queries enforced through RLS policies",
  "User uploads isolated to per-user storage buckets",
  "Rate limiting on all AI endpoints via Upstash Redis",
  "File-write paths sanitised to prevent directory traversal",
  "OAuth state validated on all Stripe Connect callbacks",
  "Advisory-lock RPC for atomic credit holds — no double-spend",
  "Admin routes guarded by is_admin profile check + middleware",
];

// ── Page ─────────────────────────────────────────────────────────────────────

export default function SecurityPage() {
  return (
    <main className="page-shell">
      <Navbar />

      {/* ── Hero ── */}
      <section className="security-hero mesh-hero">
        <div className="container">
          <AnimateIn from="fade">
            <div className="security-hero-badge">
              <ShieldCheck size={14} />
              Security
            </div>
          </AnimateIn>
          <AnimateIn from="bottom" delay={80}>
            <h1 className="security-hero-h1">
              Security is not<br />an afterthought.
            </h1>
          </AnimateIn>
          <AnimateIn from="bottom" delay={160}>
            <p className="security-hero-sub">
              SpringBloom bakes protection into every layer — the code it writes,
              the infrastructure it runs on, and the platform itself.
            </p>
          </AnimateIn>
        </div>
      </section>

      {/* ── Alternating slides ── */}
      <div className="security-slides">
        {SLIDES.map(({ icon: Icon, eyebrow, title, body, stat, statLabel }, i) => (
          <section className="security-slide" key={title}>
            <div className="container">
              <div className={`security-slide-inner ${i % 2 === 1 ? "security-slide-inner--reverse" : ""}`}>

                {/* Text side */}
                <AnimateIn from={i % 2 === 0 ? "left" : "right"} className="security-slide-text">
                  <p className="security-eyebrow">{eyebrow}</p>
                  <h2 className="security-slide-h2">{title}</h2>
                  <p className="security-slide-body">{body}</p>
                </AnimateIn>

                {/* Visual side — stat card */}
                <AnimateIn from={i % 2 === 0 ? "right" : "left"} delay={120} className="security-slide-visual">
                  <div className="security-stat-card">
                    <div className="security-stat-icon">
                      <Icon size={22} />
                    </div>
                    <p className="security-stat-number">{stat}</p>
                    <p className="security-stat-label">{statLabel}</p>
                  </div>
                </AnimateIn>

              </div>
            </div>
          </section>
        ))}
      </div>

      {/* ── Platform practices ── */}
      <section className="section bg-zinc-950">
        <div className="container">
          <AnimateIn from="bottom">
            <h2 className="text-center">Already running in production.</h2>
            <p className="section-lede text-center">
              These aren't commitments on a roadmap. Every item below is live.
            </p>
          </AnimateIn>
          <div className="security-practices">
            {PRACTICES.map((item, i) => (
              <AnimateIn from="bottom" delay={i * 50} key={item}>
                <div className="security-practice-item">
                  <CheckCircle2 className="security-practice-check" size={17} />
                  <span>{item}</span>
                </div>
              </AnimateIn>
            ))}
          </div>
        </div>
      </section>

      {/* ── Disclosure CTA ── */}
      <section className="section">
        <div className="container">
          <AnimateIn from="bottom">
            <div className="security-disclosure">
              <p className="security-eyebrow" style={{ textAlign: "center" }}>Responsible disclosure</p>
              <h2 style={{ textAlign: "center", marginTop: 12, marginBottom: 16 }}>Found a vulnerability?</h2>
              <p className="security-slide-body" style={{ textAlign: "center", maxWidth: 520, margin: "0 auto 32px" }}>
                We respond within 24 hours and publicly credit researchers who disclose responsibly.
              </p>
              <div style={{ display: "flex", justifyContent: "center" }}>
                <a className="security-cta-btn" href="mailto:security@springbloom.dev">
                  security@springbloom.dev <ArrowRight size={16} />
                </a>
              </div>
            </div>
          </AnimateIn>
        </div>
      </section>

      <Footer />
    </main>
  );
}
