/**
 * SEO/AEO File Generator
 *
 * Emits real files into the user's project repo (not a SaaS dashboard):
 *
 *   public/robots.txt        — crawler rules + AI engine allowlist
 *   public/llms.txt          — emerging standard for AI engines (ChatGPT, Perplexity)
 *   app/sitemap.ts           — Next.js dynamic sitemap (TanStack/Vite get static)
 *   lib/seo/config.ts        — typed site-wide SEO defaults
 *   lib/seo/SEO.tsx          — per-route SEO component for title/description/OG
 *
 * Dev-centric: every artifact is a real file the user can edit, version,
 * and ship. Zero ongoing cost — pure code generation.
 */

export interface SeoConfig {
  siteName:        string
  siteUrl:         string                  // https://example.com
  defaultTitle:    string
  titleTemplate?:  string                  // "%s · SiteName"
  defaultDescription: string
  defaultOgImage?: string                  // /og.png
  twitterHandle?:  string                  // @example
  locale?:         string                  // 'en-US'
  routes?:         Array<{ path: string; priority?: number; changefreq?: string }>
}

export interface GeneratedFile {
  path:     string
  content:  string
  byteSize: number
}

// ─── Entry point ────────────────────────────────────────────────────────────

export function generateSeoFiles(cfg: SeoConfig): GeneratedFile[] {
  return [
    makeFile('public/robots.txt',  buildRobotsTxt(cfg)),
    makeFile('public/llms.txt',    buildLlmsTxt(cfg)),
    makeFile('app/sitemap.ts',     buildSitemap(cfg)),
    makeFile('lib/seo/config.ts',  buildSeoConfig(cfg)),
    makeFile('lib/seo/SEO.tsx',    buildSeoComponent(cfg)),
    makeFile('lib/seo/jsonld.ts',  buildJsonLdHelpers(cfg)),
  ]
}

function makeFile(path: string, content: string): GeneratedFile {
  return { path, content, byteSize: Buffer.byteLength(content, 'utf8') }
}

// ─── robots.txt ─────────────────────────────────────────────────────────────

function buildRobotsTxt(cfg: SeoConfig): string {
  return `# robots.txt — generated by SpringBloom
# Edit freely. Restored on next SEO generation only if you delete this file.

User-agent: *
Allow: /

# AI engines (Answer Engine Optimization)
# Explicitly allow modern AI crawlers — they read llms.txt next.
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: anthropic-ai
Allow: /

# Sitemap location
Sitemap: ${cfg.siteUrl.replace(/\/$/, '')}/sitemap.xml
`
}

// ─── llms.txt (AEO emerging standard) ──────────────────────────────────────

function buildLlmsTxt(cfg: SeoConfig): string {
  const routes = cfg.routes ?? [{ path: '/' }]
  return `# ${cfg.siteName}

> ${cfg.defaultDescription}

This file follows the llms.txt convention (https://llmstxt.org) — a structured
hint for AI engines about what content is most worth indexing.

## About

${cfg.defaultDescription}

## Key Pages

${routes.map(r => `- [${r.path}](${cfg.siteUrl}${r.path})`).join('\n')}

## For AI Engines

This site welcomes AI engine indexing. See robots.txt for explicit allowlist.
Structured data (JSON-LD) is available on each page for machine-readable context.
`
}

// ─── app/sitemap.ts (Next.js App Router) ────────────────────────────────────

function buildSitemap(cfg: SeoConfig): string {
  const routes = cfg.routes ?? [{ path: '/' }]
  return `// app/sitemap.ts — generated by SpringBloom
// Next.js App Router dynamic sitemap.
// Add database-driven URLs (blog posts, products) by importing from your data layer.

import type { MetadataRoute } from 'next'

const BASE_URL = '${cfg.siteUrl.replace(/\/$/, '')}'

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: MetadataRoute.Sitemap = [
${routes.map(r =>
    `    { url: \`\${BASE_URL}${r.path}\`, lastModified: new Date(), changeFrequency: '${r.changefreq ?? 'weekly'}', priority: ${r.priority ?? 0.7} },`
  ).join('\n')}
  ]

  // TODO: append dynamic routes from your CMS/DB here
  // e.g. const posts = await db.posts.findMany(); ...

  return staticRoutes
}
`
}

// ─── lib/seo/config.ts ──────────────────────────────────────────────────────

function buildSeoConfig(cfg: SeoConfig): string {
  return `// lib/seo/config.ts — generated by SpringBloom
// Site-wide SEO defaults. Edit to your taste.

export const seoConfig = {
  siteName:           ${JSON.stringify(cfg.siteName)},
  siteUrl:            ${JSON.stringify(cfg.siteUrl)},
  defaultTitle:       ${JSON.stringify(cfg.defaultTitle)},
  titleTemplate:      ${JSON.stringify(cfg.titleTemplate ?? `%s · ${cfg.siteName}`)},
  defaultDescription: ${JSON.stringify(cfg.defaultDescription)},
  defaultOgImage:     ${JSON.stringify(cfg.defaultOgImage ?? '/og.png')},
  twitterHandle:      ${JSON.stringify(cfg.twitterHandle ?? '')},
  locale:             ${JSON.stringify(cfg.locale ?? 'en-US')},
} as const

export type SeoConfig = typeof seoConfig
`
}

// ─── lib/seo/SEO.tsx (route-level component for Next.js Metadata API) ──────

function buildSeoComponent(_cfg: SeoConfig): string {
  return `// lib/seo/SEO.tsx — generated by SpringBloom
//
// Use the Next.js Metadata API directly when possible. This helper builds a
// metadata object that fills in site-wide defaults from seoConfig.
//
// Usage in app/(routes)/page.tsx:
//
//   import { buildMetadata } from '@/lib/seo/SEO'
//
//   export const metadata = buildMetadata({
//     title: 'Pricing',
//     description: 'Simple, transparent plans.',
//     ogImage: '/og/pricing.png',
//   })

import type { Metadata } from 'next'
import { seoConfig } from './config'

export interface PageSeo {
  title?:        string
  description?:  string
  ogImage?:      string
  canonical?:    string
  noindex?:      boolean
}

export function buildMetadata(page: PageSeo = {}): Metadata {
  const title = page.title
    ? seoConfig.titleTemplate.replace('%s', page.title)
    : seoConfig.defaultTitle
  const description = page.description ?? seoConfig.defaultDescription
  const ogImage = page.ogImage ?? seoConfig.defaultOgImage
  const url = page.canonical ?? seoConfig.siteUrl

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title, description, url, siteName: seoConfig.siteName,
      images: ogImage ? [{ url: ogImage }] : undefined,
      locale: seoConfig.locale,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title, description,
      images: ogImage ? [ogImage] : undefined,
      creator: seoConfig.twitterHandle || undefined,
    },
    robots: page.noindex ? { index: false, follow: false } : { index: true, follow: true },
  }
}
`
}

// ─── lib/seo/jsonld.ts (Schema.org typed builders) ─────────────────────────

function buildJsonLdHelpers(cfg: SeoConfig): string {
  return `// lib/seo/jsonld.ts — generated by SpringBloom
//
// Typed builders for the most common Schema.org types. Returned values
// are plain objects — embed them via:
//
//   <script type="application/ld+json"
//     dangerouslySetInnerHTML={{ __html: JSON.stringify(article({ ... })) }} />
//
// Or use the <JsonLd /> component below.

import { seoConfig } from './config'
import type { ReactElement } from 'react'

const baseUrl = ${JSON.stringify(cfg.siteUrl.replace(/\/$/, ''))}

// ── Article ──────────────────────────────────────────────────────────────
export function article(input: {
  headline: string; url: string; image?: string
  datePublished: string; dateModified?: string
  authorName?: string; description?: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: input.headline,
    image: input.image ? [input.image] : undefined,
    datePublished: input.datePublished,
    dateModified: input.dateModified ?? input.datePublished,
    author: input.authorName ? { '@type': 'Person', name: input.authorName } : undefined,
    publisher: { '@type': 'Organization', name: seoConfig.siteName,
      logo: { '@type': 'ImageObject', url: baseUrl + '/logo.png' } },
    mainEntityOfPage: { '@type': 'WebPage', '@id': baseUrl + input.url },
    description: input.description,
  }
}

// ── Product ──────────────────────────────────────────────────────────────
export function product(input: {
  name: string; description: string; image?: string
  price: number; currency: string; sku?: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: input.name, description: input.description,
    image: input.image, sku: input.sku,
    offers: { '@type': 'Offer', price: input.price, priceCurrency: input.currency, availability: 'https://schema.org/InStock' },
  }
}

// ── Organization ────────────────────────────────────────────────────────
export function organization() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: seoConfig.siteName, url: baseUrl,
    logo: baseUrl + '/logo.png',
    sameAs: seoConfig.twitterHandle ? ['https://twitter.com/' + seoConfig.twitterHandle.replace('@','')] : [],
  }
}

// ── FAQ ──────────────────────────────────────────────────────────────────
export function faq(items: Array<{ question: string; answer: string }>) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map(i => ({
      '@type': 'Question', name: i.question,
      acceptedAnswer: { '@type': 'Answer', text: i.answer },
    })),
  }
}

// ── BreadcrumbList ─────────────────────────────────────────────────────
export function breadcrumbs(items: Array<{ name: string; url: string }>) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((i, idx) => ({
      '@type': 'ListItem', position: idx + 1, name: i.name, item: baseUrl + i.url,
    })),
  }
}

// ── Embed helper component ───────────────────────────────────────────────
export function JsonLd({ data }: { data: object }): ReactElement {
  return (
    // eslint-disable-next-line react/no-danger
    <script type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />
  )
}
`
}
