/**
 * A1: Stripe Webhook Handler Scaffolder.
 *
 * Lovable hides the webhook layer entirely. Devs need:
 *   - Signature verification (otherwise anyone can POST forged events)
 *   - Typed Stripe.Event switch (otherwise you forget half the events)
 *   - Idempotency table (otherwise duplicate deliveries double-charge users)
 *   - Replay-safe DB writes (otherwise retries corrupt state)
 *
 * We emit 4 files into the user's repo:
 *   - app/api/webhooks/stripe/route.ts           — the handler itself
 *   - lib/stripe/server.ts                       — typed Stripe client init
 *   - lib/stripe/events.ts                       — per-event handler functions
 *   - supabase/migrations/<ts>_stripe_events.sql — idempotency table (only
 *                                                   if user has Supabase
 *                                                   integration connected)
 */

export interface StripeScaffoldConfig {
  /** True if the project has a Supabase integration — emit the migration too */
  includeSupabaseMigration: boolean
  /** Which subscription events to handle. Defaults to common SaaS set. */
  events?: StripeEventName[]
  /** Currency for examples (informational only — doesn't affect Stripe API). */
  currency?: string
}

export type StripeEventName =
  | 'checkout.session.completed'
  | 'invoice.paid'
  | 'invoice.payment_failed'
  | 'customer.subscription.created'
  | 'customer.subscription.updated'
  | 'customer.subscription.deleted'
  | 'payment_intent.succeeded'
  | 'payment_intent.payment_failed'

const DEFAULT_EVENTS: StripeEventName[] = [
  'checkout.session.completed',
  'invoice.paid',
  'invoice.payment_failed',
  'customer.subscription.updated',
  'customer.subscription.deleted',
]

export interface GeneratedFile {
  path:     string
  content:  string
  byteSize: number
}

// ─── Public API ─────────────────────────────────────────────────────────────

export function generateStripeWebhook(cfg: StripeScaffoldConfig): GeneratedFile[] {
  const events = cfg.events && cfg.events.length > 0 ? cfg.events : DEFAULT_EVENTS

  const files: GeneratedFile[] = [
    mk('app/api/webhooks/stripe/route.ts', buildHandler(events, cfg.includeSupabaseMigration)),
    mk('lib/stripe/server.ts',             buildServerClient()),
    mk('lib/stripe/events.ts',             buildEventHandlers(events, cfg.includeSupabaseMigration)),
  ]

  if (cfg.includeSupabaseMigration) {
    const ts = new Date().toISOString().slice(0, 19).replace(/[-T:]/g, '')
    files.push(mk(`supabase/migrations/${ts}_stripe_events.sql`, buildMigration()))
  }

  return files
}

function mk(path: string, content: string): GeneratedFile {
  return { path, content, byteSize: Buffer.byteLength(content, 'utf8') }
}

// ─── lib/stripe/server.ts ───────────────────────────────────────────────────

function buildServerClient(): string {
  return `// Generated by SpringBloom — Stripe server client.
// SERVER ONLY. Never import in client components.

import Stripe from 'stripe'

const SECRET = process.env.STRIPE_SECRET_KEY
if (!SECRET) {
  // In production this should crash on boot — Stripe operations will fail anyway.
  // We log instead of throwing so dev mode can still import this file before
  // setting the env var (e.g. during scaffolding).
  console.warn('[stripe] STRIPE_SECRET_KEY is not set — Stripe calls will fail at runtime.')
}

export const stripe = new Stripe(SECRET ?? 'sk_test_unset', {
  apiVersion: '2024-12-18.acacia',
  typescript: true,
  appInfo: { name: 'SpringBloom-generated app', version: '1.0.0' },
})

/** Helper for client-side checkout — typed redirect URL builder. */
export interface CheckoutSessionInput {
  priceId:     string
  successUrl:  string
  cancelUrl:   string
  customerId?: string
  metadata?:   Record<string, string>
  mode?:       'payment' | 'subscription'
}

export async function createCheckoutSession(input: CheckoutSessionInput) {
  return stripe.checkout.sessions.create({
    mode: input.mode ?? 'subscription',
    line_items: [{ price: input.priceId, quantity: 1 }],
    success_url: input.successUrl,
    cancel_url:  input.cancelUrl,
    customer:    input.customerId,
    metadata:    input.metadata,
  })
}
`
}

// ─── app/api/webhooks/stripe/route.ts ───────────────────────────────────────

function buildHandler(events: StripeEventName[], useSupabase: boolean): string {
  return `// Generated by SpringBloom — Stripe webhook handler.
//
// Wire-up steps:
//   1. Set STRIPE_WEBHOOK_SECRET in your env (from Stripe Dashboard → Developers
//      → Webhooks → endpoint → Signing secret).
//   2. Local testing: \`stripe listen --forward-to localhost:3000/api/webhooks/stripe\`
//      Use the whsec_... it prints as STRIPE_WEBHOOK_SECRET locally.
//   3. Production: configure your endpoint URL in the Stripe Dashboard with the
//      events listed in EVENTS_HANDLED below.

import { NextResponse } from 'next/server'
import type Stripe from 'stripe'
import { stripe } from '@/lib/stripe/server'
import { handleStripeEvent } from '@/lib/stripe/events'
${useSupabase
  ? `import { createClient } from '@supabase/supabase-js'

// Service-role client — bypasses RLS, server-only.
const db = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)`
  : `// Tip: connect Supabase + re-scaffold to get a persistent idempotency table.`}

// Events this handler currently routes. Add to lib/stripe/events.ts and here.
const EVENTS_HANDLED = new Set<Stripe.Event.Type>([
${events.map((e) => `  '${e}',`).join('\n')}
])

// Next.js: don't pre-parse the body — Stripe needs the raw string for signature verification.
export const runtime = 'nodejs'

export async function POST(req: Request) {
  const sig = req.headers.get('stripe-signature')
  if (!sig) return NextResponse.json({ error: 'Missing stripe-signature header' }, { status: 400 })

  const secret = process.env.STRIPE_WEBHOOK_SECRET
  if (!secret) {
    console.error('[stripe-webhook] STRIPE_WEBHOOK_SECRET is not configured')
    return NextResponse.json({ error: 'Server misconfigured' }, { status: 500 })
  }

  // Raw body required — getReader keeps it byte-exact.
  const rawBody = await req.text()

  let event: Stripe.Event
  try {
    event = stripe.webhooks.constructEvent(rawBody, sig, secret)
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Signature verification failed'
    console.warn('[stripe-webhook] Signature verification failed:', msg)
    return NextResponse.json({ error: \`Invalid signature: \${msg}\` }, { status: 400 })
  }

  ${useSupabase ? `// Idempotency check — bail early if we've already processed this event.
  // Stripe retries failed deliveries; without this, duplicate row inserts and
  // double-charges are guaranteed.
  const { error: insertErr } = await db
    .from('stripe_events')
    .insert({ id: event.id, type: event.type, payload: event as unknown })
  if (insertErr) {
    // PostgrestError 23505 is unique_violation — same event id already stored.
    if ((insertErr as { code?: string }).code === '23505') {
      console.log(\`[stripe-webhook] Duplicate event \${event.id} — already processed.\`)
      return NextResponse.json({ received: true, duplicate: true })
    }
    console.error('[stripe-webhook] Could not record event:', insertErr)
    return NextResponse.json({ error: 'Storage failed' }, { status: 500 })
  }` : `// No idempotency layer (Supabase not connected). Stripe WILL retry on
  // 5xx responses; if your handler is not idempotent, you'll see double-writes.`}

  // Skip events we don't handle — still ACK them so Stripe stops retrying.
  if (!EVENTS_HANDLED.has(event.type)) {
    return NextResponse.json({ received: true, handled: false })
  }

  try {
    await handleStripeEvent(event)
    return NextResponse.json({ received: true, handled: true })
  } catch (err) {
    // Return 500 → Stripe will retry with exponential backoff (up to 3 days).
    // Make sure handleStripeEvent is idempotent if you re-throw.
    console.error(\`[stripe-webhook] \${event.type} handler failed:\`, err)
    return NextResponse.json({ error: 'Handler failed' }, { status: 500 })
  }
}
`
}

// ─── lib/stripe/events.ts ───────────────────────────────────────────────────

function buildEventHandlers(events: StripeEventName[], useSupabase: boolean): string {
  const handlers = events.map(buildSingleHandler).join('\n\n')
  return `// Generated by SpringBloom — per-event Stripe handlers.
//
// Each handler is wired into route.ts. Add business logic inside the marked
// // TODO blocks. The handlers should be idempotent — Stripe retries.

import type Stripe from 'stripe'
${useSupabase
  ? `import { createClient } from '@supabase/supabase-js'

const db = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)`
  : ''}

export async function handleStripeEvent(event: Stripe.Event): Promise<void> {
  switch (event.type) {
${events.map((e) => `    case '${e}': return on_${eventSlug(e)}(event)`).join('\n')}
    default:
      // Defensive — should be filtered before we get here.
      console.warn(\`[stripe] Unhandled event type: \${event.type}\`)
  }
}

${handlers}
`
}

function buildSingleHandler(event: StripeEventName): string {
  const slug = eventSlug(event)
  const objectTypeHint: Record<StripeEventName, string> = {
    'checkout.session.completed':       'Stripe.Checkout.Session',
    'invoice.paid':                     'Stripe.Invoice',
    'invoice.payment_failed':           'Stripe.Invoice',
    'customer.subscription.created':    'Stripe.Subscription',
    'customer.subscription.updated':    'Stripe.Subscription',
    'customer.subscription.deleted':    'Stripe.Subscription',
    'payment_intent.succeeded':         'Stripe.PaymentIntent',
    'payment_intent.payment_failed':    'Stripe.PaymentIntent',
  }
  const type = objectTypeHint[event] ?? 'unknown'

  return `async function on_${slug}(event: Stripe.Event): Promise<void> {
  const obj = event.data.object as ${type}
  // TODO: handle ${event}
  // Example fields available on \`obj\`:
  //   - obj.id, obj.customer, obj.metadata, obj.status
  // Remember: this handler MUST be idempotent. Stripe will retry on 5xx.
  console.log(\`[stripe] ${event}: \${obj.id}\`)
}`
}

function eventSlug(event: StripeEventName): string {
  return event.replace(/\./g, '_')
}

// ─── supabase/migrations/<ts>_stripe_events.sql ────────────────────────────

function buildMigration(): string {
  return `-- Stripe webhook idempotency table — generated by SpringBloom.
--
-- Every Stripe event arrives with a unique id (evt_xxx). We insert it on
-- receipt; the primary key constraint blocks duplicates so retries don't
-- cause double-writes.

create table if not exists public.stripe_events (
  id          text primary key,                    -- evt_xxx
  type        text not null,                       -- e.g. checkout.session.completed
  payload     jsonb not null,                      -- full event for replay/debug
  received_at timestamptz not null default now()
);

create index if not exists idx_stripe_events_type on public.stripe_events(type);
create index if not exists idx_stripe_events_received on public.stripe_events(received_at desc);

-- Service role only — never expose this to authenticated/anon clients.
alter table public.stripe_events enable row level security;

comment on table public.stripe_events is
  'Idempotency log for Stripe webhook deliveries. Insert on event receipt; PK blocks duplicates.';
`
}
