/**
 * R4-6: Playwright scaffold.
 *
 * Drops a working Playwright setup into the user's repo:
 *   - playwright.config.ts        — base config, sensible defaults, CI-aware
 *   - e2e/example.spec.ts          — smoke test against /
 *   - e2e/auth.spec.ts             — opt-in: signed-in flow scaffold
 *   - .github/workflows/e2e.yml    — opt-in: GitHub Actions runner
 *   - playwright.gitignore         — snippet to append to .gitignore (we don't merge yet)
 *
 * No sidecar Fly machines yet — tests run inside the existing project machine
 * via the existing /tests/run SSE route. Browser binaries are downloaded
 * on first run by `npx playwright install`.
 */

export interface PlaywrightScaffoldConfig {
  /** Base URL the tests hit. Defaults to the project's preview URL. */
  baseUrl?:        string
  /** Include a signed-in flow example test. */
  includeAuth?:    boolean
  /** Emit a GitHub Actions workflow that runs the tests on PR. */
  includeCi?:      boolean
}

export interface GeneratedFile { path: string; content: string; byteSize: number }

export function generatePlaywrightScaffold(cfg: PlaywrightScaffoldConfig = {}): GeneratedFile[] {
  const baseUrl = cfg.baseUrl ?? 'http://localhost:3000'

  const files: GeneratedFile[] = [
    mk('playwright.config.ts', buildConfig(baseUrl)),
    mk('e2e/example.spec.ts',  buildExampleSpec()),
  ]
  if (cfg.includeAuth) {
    files.push(mk('e2e/auth.spec.ts', buildAuthSpec()))
  }
  if (cfg.includeCi) {
    files.push(mk('.github/workflows/e2e.yml', buildCiWorkflow()))
  }
  files.push(mk('e2e/README.md', buildReadme(cfg.includeAuth, cfg.includeCi)))
  return files
}

function mk(path: string, content: string): GeneratedFile {
  return { path, content, byteSize: Buffer.byteLength(content, 'utf8') }
}

// ─── playwright.config.ts ───────────────────────────────────────────────────

function buildConfig(baseUrl: string): string {
  return `// Generated by SpringBloom — Playwright config.
// Docs: https://playwright.dev/docs/test-configuration

import { defineConfig, devices } from '@playwright/test'

const PORT = process.env.PORT ?? '3000'
const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? '${baseUrl}'

export default defineConfig({
  testDir:  './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries:  process.env.CI ? 2 : 0,
  workers:  process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? [['github'], ['html', { open: 'never' }]] : 'list',
  use: {
    baseURL: BASE_URL,
    trace:   'on-first-retry',
    screenshot: 'only-on-failure',
    video:   'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    // Uncomment to broaden coverage:
    // { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    // { name: 'webkit',  use: { ...devices['Desktop Safari'] } },
    // { name: 'mobile-chrome', use: { ...devices['Pixel 5'] } },
  ],
  // Spawn dev server for local runs (skipped in CI if the URL is reachable).
  webServer: process.env.CI ? undefined : {
    command: 'npm run dev',
    port:    Number(PORT),
    reuseExistingServer: true,
    timeout: 120_000,
  },
})
`
}

// ─── e2e/example.spec.ts ────────────────────────────────────────────────────

function buildExampleSpec(): string {
  return `// Generated by SpringBloom — Playwright smoke test.

import { test, expect } from '@playwright/test'

test('homepage loads', async ({ page }) => {
  await page.goto('/')
  // Replace with a stable selector once you know your hero copy:
  await expect(page).toHaveTitle(/.+/)
})

test('homepage has navigable links', async ({ page }) => {
  await page.goto('/')
  const links = page.getByRole('link')
  // At least one link should be present.
  await expect(links.first()).toBeVisible()
})

test('no console errors on load', async ({ page }) => {
  const errors: string[] = []
  page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
  await page.goto('/')
  await page.waitForLoadState('networkidle')
  // Allow benign React dev-warnings; fail on actual errors.
  const real = errors.filter((e) => !/Warning:/.test(e))
  expect(real, real.join('\\n')).toHaveLength(0)
})
`
}

// ─── e2e/auth.spec.ts (opt-in) ──────────────────────────────────────────────

function buildAuthSpec(): string {
  return `// Generated by SpringBloom — signed-in flow scaffold.
//
// Replace EMAIL/PASSWORD with test-user credentials. Recommended: create a
// test user via Supabase admin SDK in a global setup, then store the
// auth cookies for reuse across specs.

import { test, expect } from '@playwright/test'

const EMAIL = process.env.TEST_USER_EMAIL ?? 'test@example.com'
const PASSWORD = process.env.TEST_USER_PASSWORD ?? 'changeme'

test.describe('authenticated user flow', () => {
  test('sign in and reach dashboard', async ({ page }) => {
    await page.goto('/login')
    await page.getByLabel(/email/i).fill(EMAIL)
    await page.getByLabel(/password/i).fill(PASSWORD)
    await page.getByRole('button', { name: /sign in/i }).click()
    await expect(page).toHaveURL(/\\/dashboard/)
  })

  test('unauthenticated visit redirects to login', async ({ browser }) => {
    const context = await browser.newContext({ storageState: { cookies: [], origins: [] } })
    const page = await context.newPage()
    await page.goto('/dashboard')
    await expect(page).toHaveURL(/\\/login/)
    await context.close()
  })
})
`
}

// ─── .github/workflows/e2e.yml (opt-in) ─────────────────────────────────────

function buildCiWorkflow(): string {
  return `# Generated by SpringBloom — Playwright on PR.
name: e2e

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build
      - run: npx playwright test
        env:
          # Add any env vars the app needs at build/runtime here:
          NEXT_PUBLIC_SUPABASE_URL: \${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: \${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
`
}

// ─── e2e/README.md ──────────────────────────────────────────────────────────

function buildReadme(includeAuth?: boolean, includeCi?: boolean): string {
  return `# Playwright tests

Generated by SpringBloom.

## Run locally

\`\`\`bash
# One-time: install browser binaries (~150MB chromium)
npx playwright install --with-deps chromium

# Run all tests
npx playwright test

# Watch mode (rerun on file change)
npx playwright test --ui

# Open the HTML report after a failed run
npx playwright show-report
\`\`\`

## Run from SpringBloom

Open the **Tests** tab in the builder. It auto-detects Playwright and runs
\`npx playwright test\` inside your project's Fly machine. Output appears in
the panel.

## Files

- \`playwright.config.ts\` — projects, baseURL, dev server config
- \`e2e/example.spec.ts\` — homepage smoke tests
${includeAuth ? '- `e2e/auth.spec.ts` — signed-in flow scaffold (edit credentials)' : ''}
${includeCi ? '- `.github/workflows/e2e.yml` — runs on PR + push to main' : ''}

## Tips

- Use \`page.getByRole('button', { name: /save/i })\` over CSS selectors — more
  resilient to redesigns and forces accessible markup.
- Snapshot tests: \`await expect(page).toHaveScreenshot()\` then commit the PNGs.
- Trace viewer: when a test fails, \`npx playwright show-trace trace.zip\` opens
  a time-travel debugger.
`
}
