-- Migration 032: Plan / Agent / Code Modes
--
-- Adds three execution modes to the chat builder:
--
--   plan   → produce an editable implementation plan only (no code writes)
--   agent  → autonomous: write code + run tests/typecheck + iterate (default)
--   code   → fast diff-only edits, minimal prose, cheapest model
--
-- Each message records the mode it was generated under. Plans live in their own
-- table so the user can edit + approve the markdown before execution kicks off.

-- ── messages.mode ──────────────────────────────────────────────────────────

alter table public.messages
  add column if not exists mode text default 'agent'
    check (mode in ('plan', 'agent', 'code'));

alter table public.messages
  add column if not exists dry_run boolean not null default false;

-- ── projects.default_mode (per-project preference) ────────────────────────

alter table public.projects
  add column if not exists default_mode text default 'agent'
    check (default_mode in ('plan', 'agent', 'code'));

-- ── plans table ───────────────────────────────────────────────────────────
-- One row per plan generated by Plan mode. The user can edit the markdown
-- before approving. On approval, the plan body is fed back into Agent mode
-- as system context for execution.

create table if not exists public.plans (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid references public.projects(id) on delete cascade not null,
  user_id         uuid references auth.users(id) on delete cascade not null,
  message_id      uuid references public.messages(id) on delete set null,
  -- Original plan markdown produced by the AI
  markdown        text not null,
  -- User-edited version (if any) — final source of truth for execution
  edited_markdown text,
  status          text not null default 'draft'
    check (status in ('draft', 'approved', 'executed', 'discarded')),
  approved_at     timestamptz,
  executed_at     timestamptz,
  -- Token usage for cost tracking
  input_tokens    int default 0,
  output_tokens   int default 0,
  created_at      timestamptz not null default now()
);

create index if not exists idx_plans_project on public.plans(project_id, created_at desc);

alter table public.plans enable row level security;
create policy "users own their plans"
  on public.plans for all using (auth.uid() = user_id);

comment on table  public.plans is 'Plan-mode outputs. Stored separately so users can edit before execution.';
comment on column public.messages.mode is 'plan | agent | code — execution mode for this turn.';
