-- ═══════════════════════════════════════════════════════════════════════
-- ALL_032_to_040.sql — combined catch-up migration
--
-- Run this ONCE in the Supabase SQL editor to apply migrations 032–040
-- in order. Every statement is idempotent (`if not exists`, `if not` etc.)
-- so re-running is safe.
--
-- Order matters: 040 references knowledge_docs which is created in 033.
-- The Tools section (DELETE FROM pg_extension idempotency) is at top.
-- ═══════════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────────
-- 032_message_modes.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 032: Plan / Agent / Code Modes
--
-- Adds three execution modes to the chat builder:
--
--   plan   → produce an editable implementation plan only (no code writes)
--   agent  → autonomous: write code + run tests/typecheck + iterate (default)
--   code   → fast diff-only edits, minimal prose, cheapest model
--
-- Each message records the mode it was generated under. Plans live in their own
-- table so the user can edit + approve the markdown before execution kicks off.

-- ── messages.mode ──────────────────────────────────────────────────────────

alter table public.messages
  add column if not exists mode text default 'agent'
    check (mode in ('plan', 'agent', 'code'));

alter table public.messages
  add column if not exists dry_run boolean not null default false;

-- ── projects.default_mode (per-project preference) ────────────────────────

alter table public.projects
  add column if not exists default_mode text default 'agent'
    check (default_mode in ('plan', 'agent', 'code'));

-- ── plans table ───────────────────────────────────────────────────────────
-- One row per plan generated by Plan mode. The user can edit the markdown
-- before approving. On approval, the plan body is fed back into Agent mode
-- as system context for execution.

create table if not exists public.plans (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid references public.projects(id) on delete cascade not null,
  user_id         uuid references auth.users(id) on delete cascade not null,
  message_id      uuid references public.messages(id) on delete set null,
  -- Original plan markdown produced by the AI
  markdown        text not null,
  -- User-edited version (if any) — final source of truth for execution
  edited_markdown text,
  status          text not null default 'draft'
    check (status in ('draft', 'approved', 'executed', 'discarded')),
  approved_at     timestamptz,
  executed_at     timestamptz,
  -- Token usage for cost tracking
  input_tokens    int default 0,
  output_tokens   int default 0,
  created_at      timestamptz not null default now()
);

create index if not exists idx_plans_project on public.plans(project_id, created_at desc);

alter table public.plans enable row level security;
create policy "users own their plans"
  on public.plans for all using (auth.uid() = user_id);

comment on table  public.plans is 'Plan-mode outputs. Stored separately so users can edit before execution.';
comment on column public.messages.mode is 'plan | agent | code — execution mode for this turn.';


-- ──────────────────────────────────────────────────────────────────
-- 033_knowledge.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 033: Knowledge — three-tier file-first context system
--
-- Unlike Lovable's 10k-char textareas, SpringBloom stores knowledge
-- in real files (AGENTS.md in the project repo) so it ships with the code
-- and is portable to Cursor, Claude Code, Copilot, etc.
--
-- Three tiers (project tier lives in the repo, not the DB):
--
--   1. user_knowledge      → DB table, applies to every project the user creates
--                            (preferred stack, lint rules, banned libraries)
--   2. project AGENTS.md   → file in the project repo, single source of truth
--                            (read by builder on every turn, version-controlled)
--   3. reference docs      → RAG candidates, attached files/URLs chunked into
--                            knowledge_chunks (pgvector). Built later.
--
-- This migration sets up tiers 1 and 3 (the table-based ones).

-- ── User-level knowledge ────────────────────────────────────────────────────

create table if not exists public.user_knowledge (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid references auth.users(id) on delete cascade not null unique,
  -- Free-form markdown — preferences that apply to every project
  -- (preferred stack, lint rules, banned libraries, comment style)
  content        text not null default '',
  -- Token budget hint — caller can use this to truncate before injection
  max_tokens     int  not null default 1500,
  updated_at     timestamptz not null default now()
);

alter table public.user_knowledge enable row level security;
create policy "users own their knowledge"
  on public.user_knowledge for all using (auth.uid() = user_id);

-- ── Reference docs (for future RAG) ─────────────────────────────────────────
-- Stores user-attached docs (OpenAPI specs, READMEs, design briefs).
-- Chunks live in a separate table so we can swap embedding providers.

create table if not exists public.knowledge_docs (
  id             uuid primary key default gen_random_uuid(),
  project_id     uuid references public.projects(id) on delete cascade,  -- null = user-global
  user_id        uuid references auth.users(id) on delete cascade not null,
  source_type    text not null check (source_type in ('upload', 'url', 'github', 'openapi', 'readme')),
  source_url     text,
  filename       text,
  content        text not null,                  -- raw text
  byte_size      int  not null default 0,
  -- Set when chunks have been generated + embedded
  indexed_at     timestamptz,
  created_at     timestamptz not null default now()
);

create index if not exists idx_knowledge_docs_project on public.knowledge_docs(project_id);
create index if not exists idx_knowledge_docs_user    on public.knowledge_docs(user_id);

alter table public.knowledge_docs enable row level security;
create policy "users own their knowledge docs"
  on public.knowledge_docs for all using (auth.uid() = user_id);

-- knowledge_chunks (pgvector) table comes in a follow-up migration once
-- vector extension setup is finalized.

comment on table public.user_knowledge is
  'Per-user always-injected context (file-first equivalent: ~/.springbloom/AGENTS.md). Project AGENTS.md overrides this.';
comment on table public.knowledge_docs is
  'Reference docs attached by user. Will be chunked + embedded for RAG retrieval per turn.';


-- ──────────────────────────────────────────────────────────────────
-- 034_custom_domains.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 034: Custom Domains via Cloudflare for SaaS
--
-- Stores user-attached domains for published projects. Uses Cloudflare's
-- Custom Hostnames API — free SSL provisioning, automatic cert renewal,
-- no per-hostname fee.
--
-- DNS state machine:  pending → verifying → active → failed
-- SSL state machine:  pending → validating → active → failed
--
-- A project can have multiple domains (apex + subdomains + redirects).
-- One per project can be marked is_primary for the canonical URL.

create table if not exists public.custom_domains (
  id                       uuid primary key default gen_random_uuid(),
  project_id               uuid references public.projects(id) on delete cascade not null,
  user_id                  uuid references auth.users(id) on delete cascade not null,
  hostname                 text not null,
  -- Cloudflare Custom Hostname resource id (set after CF API create)
  cf_custom_hostname_id    text,
  -- Cloudflare verification record values — surfaced to the user verbatim
  verification_record_type text default 'TXT',
  verification_record_name text,
  verification_record_value text,
  -- DNS / SSL status, kept in sync from CF polls
  dns_status               text not null default 'pending'
    check (dns_status in ('pending', 'verifying', 'active', 'failed')),
  ssl_status               text not null default 'pending'
    check (ssl_status in ('pending', 'validating', 'active', 'failed')),
  last_status_message      text,
  is_primary               boolean not null default false,
  last_checked_at          timestamptz,
  created_at               timestamptz not null default now(),
  unique (project_id, hostname)
);

create index if not exists idx_custom_domains_project on public.custom_domains(project_id);
create index if not exists idx_custom_domains_user    on public.custom_domains(user_id);

alter table public.custom_domains enable row level security;
create policy "users own their custom domains"
  on public.custom_domains for all using (auth.uid() = user_id);

-- Only one primary per project (enforced via partial unique index)
create unique index if not exists idx_custom_domains_one_primary
  on public.custom_domains(project_id)
  where is_primary = true;

comment on table  public.custom_domains is 'Per-project custom domains backed by Cloudflare Custom Hostnames API.';
comment on column public.custom_domains.is_primary is 'Canonical URL — only one per project (partial unique index enforces).';


-- ──────────────────────────────────────────────────────────────────
-- 035_cache_telemetry.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 035: Prompt cache telemetry on agent_runs
--
-- After wiring Anthropic prompt caching (R0-1), we need to know whether
-- the cache is actually hitting in production. Without these columns we'd
-- be flying blind on the most important cost optimization in the stack.
--
-- Anthropic's API returns:
--   cache_creation_input_tokens — first-time tokens written into the cache
--                                  (charged at 1.25× normal input price)
--   cache_read_input_tokens     — tokens served from cache (10% of normal price)
--
-- Cache hit rate = cache_read / (cache_read + cache_creation + cached_eligible_input)
-- Aim for >70% on warm sessions.

alter table public.agent_runs
  add column if not exists cache_creation_input_tokens int default 0,
  add column if not exists cache_read_input_tokens     int default 0;

comment on column public.agent_runs.cache_creation_input_tokens is
  'Anthropic prompt-cache write tokens (charged 1.25× normal). High on cold turns.';
comment on column public.agent_runs.cache_read_input_tokens is
  'Anthropic prompt-cache read tokens (charged 0.1× normal). Should dominate on warm sessions.';


-- ──────────────────────────────────────────────────────────────────
-- 036_deployments.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 036: Deployment history
--
-- Currently `projects` stores a single cloudflare_deployment_id — we overwrite
-- it on every publish, losing history. This table records every publish
-- attempt so we can:
--   - Show a deployment timeline in PublishModal
--   - Roll back to a previous deployment via Cloudflare API
--   - Debug failed publishes (build_log preserved)
--   - Measure publish reliability over time

create table if not exists public.deployments (
  id                     uuid primary key default gen_random_uuid(),
  project_id             uuid references public.projects(id) on delete cascade not null,
  user_id                uuid references auth.users(id) on delete cascade not null,
  -- Cloudflare resource ids
  cf_project_name        text,
  cf_deployment_id       text,
  published_url          text,
  -- State machine: pending → building → uploading → success | failed | cancelled
  status                 text not null default 'pending'
    check (status in ('pending', 'building', 'uploading', 'success', 'failed', 'cancelled')),
  -- Build artifact metadata
  build_log              text,                   -- captured stdout/stderr (truncated to ~64KB)
  build_duration_ms      int,
  bundle_size_bytes      bigint,
  file_count             int,
  -- Failure info
  error_message          text,
  -- Promotion (preview vs production split — future use)
  is_production          boolean not null default true,
  rolled_back_at         timestamptz,
  created_at             timestamptz not null default now(),
  completed_at           timestamptz
);

create index if not exists idx_deployments_project on public.deployments(project_id, created_at desc);
create index if not exists idx_deployments_user on public.deployments(user_id);

alter table public.deployments enable row level security;
create policy "users own their deployments"
  on public.deployments for all using (auth.uid() = user_id);

comment on table  public.deployments is
  'One row per publish attempt. Replaces the single fly_machine fields on projects (those stay for current-live convenience).';
comment on column public.deployments.build_log is
  'Captured npm run build stdout/stderr. Truncated to ~64KB to keep rows small.';
comment on column public.deployments.is_production is
  'False for preview branches (future). True for primary production deployments.';


-- ──────────────────────────────────────────────────────────────────
-- 037_security_notes.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 037: Security Notes (generation-time auto-capture)
--
-- This is the UNIQUE differentiator vs Lovable. Lovable's "security memory"
-- is a manual textarea the user maintains. Ours auto-populates whenever the
-- AI writes security-relevant code (RLS policies, auth checks, raw SQL,
-- eval, webhook signature verification, etc.).
--
-- Each note records:
--   - WHAT we detected (category + title + matched snippet)
--   - WHERE (file + line range from the artifact)
--   - WHEN (linked to the agent_run that produced it)
--
-- The security scanner reads these notes as context, so it can give better
-- recommendations without re-deriving everything from scratch.

create table if not exists public.security_notes (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid references public.projects(id) on delete cascade not null,
  user_id       uuid references auth.users(id) on delete cascade not null,
  agent_run_id  uuid references public.agent_runs(id) on delete set null,
  -- Where we saw it
  source        text not null check (source in ('generation', 'user', 'scanner')),
  category      text not null,           -- 'rls', 'auth', 'secrets', 'webhook', 'sql', 'eval', etc.
  pattern       text,                    -- the rule that matched (e.g. 'enable_rls')
  -- Content
  title         text not null,
  snippet       text,                    -- the matched code excerpt (truncated)
  file_path     text,
  line_start    int,
  line_end      int,
  -- Disposition
  accepted_risk boolean not null default false,
  accepted_at   timestamptz,
  accepted_note text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_security_notes_project  on public.security_notes(project_id, created_at desc);
create index if not exists idx_security_notes_category on public.security_notes(project_id, category);
create index if not exists idx_security_notes_run      on public.security_notes(agent_run_id);

alter table public.security_notes enable row level security;
create policy "users own their security notes"
  on public.security_notes for all using (auth.uid() = user_id);

comment on table  public.security_notes is
  'Auto-captured security observations from AI-generated code. Differentiator vs Lovable (their security memory is manual-only).';
comment on column public.security_notes.source is
  'generation = auto from LLM stream | user = manual entry | scanner = surfaced by security scan';


-- ──────────────────────────────────────────────────────────────────
-- 038_user_snippets.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 038: User snippets / skills library
--
-- Reusable instruction packages a user saves once and triggers across projects
-- via `/snippet-name` slash commands in chat OR auto-suggested via NLP match.
--
-- Inspired by Lovable's "Skills" (markdown context packages), but stored
-- per-user (workspace-scoped — applies across all projects of this user) and
-- importable from `.cursor/rules/*.mdc`, `AGENTS.md`, `CLAUDE.md`.

create table if not exists public.user_snippets (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users(id) on delete cascade not null,
  -- Trigger handle: typing `/<trigger>` in chat injects this snippet's body
  trigger         text not null,                  -- kebab-case, e.g. "drizzle-migration"
  label           text not null,                  -- human-readable name
  description     text,                           -- "Use when..." — drives NLP matching
  body            text not null,                  -- markdown or code that gets injected
  tags            text[] not null default '{}',
  -- Provenance
  source          text not null default 'manual'
    check (source in ('manual', 'cursor', 'agents', 'github', 'imported')),
  source_url      text,                           -- GitHub URL if imported
  -- Usage tracking — let users see which snippets they actually use
  use_count       int  not null default 0,
  last_used_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (user_id, trigger)
);

create index if not exists idx_user_snippets_user on public.user_snippets(user_id, created_at desc);

alter table public.user_snippets enable row level security;
create policy "users own their snippets"
  on public.user_snippets for all using (auth.uid() = user_id);

comment on table public.user_snippets is
  'Reusable markdown/code snippets the user triggers via /<trigger> slash commands. Cross-project, workspace-scoped.';


-- ──────────────────────────────────────────────────────────────────
-- 040_knowledge_chunks.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 040: Knowledge doc chunks (RAG-lite)
--
-- For now we use ILIKE search (no embeddings yet). pgvector + embeddings is
-- the next step; this schema is already vector-ready (just add an embedding
-- column later and a separate index).
--
-- Each `knowledge_doc` (already exists, migration 033) is split into chunks
-- of ~500 chars at paragraph/sentence boundaries. At chat time we ILIKE the
-- user's prompt against chunk_text and inject top-K matches into context.

create table if not exists public.knowledge_doc_chunks (
  id           uuid primary key default gen_random_uuid(),
  doc_id       uuid references public.knowledge_docs(id) on delete cascade not null,
  user_id      uuid references auth.users(id) on delete cascade not null,
  project_id   uuid references public.projects(id) on delete cascade,  -- nullable: user-global docs
  chunk_index  int not null,
  chunk_text   text not null,
  -- char range in the original doc for citation
  char_start   int not null,
  char_end     int not null,
  -- Future: pgvector embedding column
  -- embedding  vector(1536),
  created_at   timestamptz not null default now(),
  unique (doc_id, chunk_index)
);

create index if not exists idx_chunks_doc      on public.knowledge_doc_chunks(doc_id);
create index if not exists idx_chunks_user     on public.knowledge_doc_chunks(user_id);
create index if not exists idx_chunks_project  on public.knowledge_doc_chunks(project_id);
-- Trigram GIN index for fast ILIKE matching (pg_trgm should be enabled).
-- If not enabled in user DB, falls back to seq scan — still works.
create extension if not exists pg_trgm;
create index if not exists idx_chunks_trgm
  on public.knowledge_doc_chunks using gin (chunk_text gin_trgm_ops);

alter table public.knowledge_doc_chunks enable row level security;
create policy "users own their knowledge chunks"
  on public.knowledge_doc_chunks for all using (auth.uid() = user_id);

comment on table public.knowledge_doc_chunks is
  'Pre-chunked text from knowledge_docs for RAG retrieval. ILIKE-based today, pgvector-ready.';

