/**
 * B1: Auth Scaffold — code-level companions to the Auth Providers panel.
 *
 * Drops a production-grade auth surface into the user's repo:
 *   - app/auth/callback/route.ts            — handles OAuth + magic link redirect
 *   - app/auth/signout/route.ts             — POST signout endpoint
 *   - lib/auth/server.ts                    — typed createClient for RSC + routes
 *   - lib/auth/client.ts                    — typed createClient for browser
 *   - middleware.ts                         — session refresh + protected routes
 *   - lib/auth/jwt-hook-template.sql        — opt-in Postgres function for custom JWT claims
 *   - app/(auth)/mfa/page.tsx               — opt-in TOTP enroll/verify UI
 *
 * Each piece is independently togglable. Lovable hides all of this — devs
 * want the actual files so they can extend, audit, and own the auth surface.
 */

export interface AuthScaffoldConfig {
  /** Frameworks the scaffold targets — currently only Next.js App Router */
  framework?: 'next-app'
  /** Include MFA enrollment + verify components */
  includeMfa?: boolean
  /** Include custom JWT claims template (Postgres function) */
  includeJwtHook?: boolean
  /** Comma-separated list of protected route patterns (for middleware) */
  protectedRoutes?: string[]
}

export interface GeneratedFile {
  path:     string
  content:  string
  byteSize: number
}

// ─── Public entry point ─────────────────────────────────────────────────────

export function generateAuthScaffold(cfg: AuthScaffoldConfig = {}): GeneratedFile[] {
  const files: GeneratedFile[] = [
    mk('app/auth/callback/route.ts',  buildCallback()),
    mk('app/auth/signout/route.ts',   buildSignout()),
    mk('lib/auth/server.ts',          buildServerClient()),
    mk('lib/auth/client.ts',          buildBrowserClient()),
    mk('middleware.ts',               buildMiddleware(cfg.protectedRoutes ?? ['/dashboard', '/settings'])),
  ]
  if (cfg.includeMfa) {
    files.push(mk('app/(auth)/mfa/page.tsx',           buildMfaPage()))
    files.push(mk('app/(auth)/mfa/enroll-action.ts',   buildMfaEnrollAction()))
  }
  if (cfg.includeJwtHook) {
    files.push(mk('supabase/migrations/' + tsName() + '_custom_access_token_hook.sql', buildJwtHookSql()))
  }
  return files
}

function mk(path: string, content: string): GeneratedFile {
  return { path, content, byteSize: Buffer.byteLength(content, 'utf8') }
}

function tsName(): string {
  return new Date().toISOString().slice(0, 19).replace(/[-T:]/g, '')
}

// ─── Files ──────────────────────────────────────────────────────────────────

function buildCallback(): string {
  return `// Generated by SpringBloom — OAuth + magic-link callback handler.
// Reached after a successful sign-in via Google/Apple/Facebook/GitHub OR
// after the user clicks the magic-link sent to their email.

import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/auth/server'

export async function GET(req: Request) {
  const url = new URL(req.url)
  const code = url.searchParams.get('code')
  // Where to redirect after auth completes. Defaults to /dashboard.
  const next = url.searchParams.get('next') ?? '/dashboard'

  if (!code) {
    return NextResponse.redirect(\`\${url.origin}/login?error=missing_code\`)
  }

  const supabase = await createServerClient()
  const { error } = await supabase.auth.exchangeCodeForSession(code)
  if (error) {
    console.error('[auth/callback] exchange failed:', error.message)
    return NextResponse.redirect(\`\${url.origin}/login?error=\${encodeURIComponent(error.message)}\`)
  }

  // TODO (optional): run first-login hooks here.
  //   - create a profiles row
  //   - assign default plan
  //   - send a welcome email

  return NextResponse.redirect(\`\${url.origin}\${next}\`)
}
`
}

function buildSignout(): string {
  return `// Generated by SpringBloom — signout endpoint.
// POST here from your nav menu / settings button.

import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/auth/server'

export async function POST(req: Request) {
  const supabase = await createServerClient()
  await supabase.auth.signOut()
  const origin = new URL(req.url).origin
  return NextResponse.redirect(\`\${origin}/\`, { status: 303 })
}
`
}

function buildServerClient(): string {
  return `// Generated by SpringBloom — Supabase server client for Server Components + Route Handlers.
// SSR-safe: reads/writes cookies via Next.js cookies() API so the session
// stays consistent across server renders.

import { createServerClient as _create } from '@supabase/ssr'
import { cookies } from 'next/headers'

export async function createServerClient() {
  const cookieStore = await cookies()
  return _create(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll(toSet) {
          try { toSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options)) }
          catch { /* called from a Server Component — middleware handles refresh */ }
        },
      },
    },
  )
}
`
}

function buildBrowserClient(): string {
  return `// Generated by SpringBloom — Supabase browser client for "use client" components.

import { createBrowserClient } from '@supabase/ssr'

export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  )
}
`
}

function buildMiddleware(protectedPatterns: string[]): string {
  const matcherJs = JSON.stringify(protectedPatterns.map((p) => `${p}/:path*`))
  return `// Generated by SpringBloom — refreshes the user's session on every request,
// and bounces unauthenticated visitors away from protected routes.

import { type NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'

const PROTECTED = ${JSON.stringify(protectedPatterns)}

export async function middleware(request: NextRequest) {
  let response = NextResponse.next({ request })

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return request.cookies.getAll() },
        setAll(toSet) {
          toSet.forEach(({ name, value, options }) => {
            request.cookies.set(name, value)
            response = NextResponse.next({ request })
            response.cookies.set(name, value, options)
          })
        },
      },
    },
  )

  // IMPORTANT: getUser() refreshes the session if the access token is stale.
  const { data: { user } } = await supabase.auth.getUser()

  // Redirect unauthenticated users to /login on protected routes
  const path = request.nextUrl.pathname
  const isProtected = PROTECTED.some((p) => path === p || path.startsWith(p + '/'))
  if (!user && isProtected) {
    const url = request.nextUrl.clone()
    url.pathname = '/login'
    url.searchParams.set('next', path)
    return NextResponse.redirect(url)
  }

  return response
}

export const config = {
  // Match everything except static assets + Next internals.
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|.*\\\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}

// Matcher patterns above run middleware globally; we filter to PROTECTED inside.
// You can also restrict matcher itself to: ${matcherJs}
`
}

function buildMfaPage(): string {
  return `// Generated by SpringBloom — TOTP MFA enroll & verify (Supabase Auth).

"use client"

import { useEffect, useState } from "react"
import { createClient } from "@/lib/auth/client"
import { enrollMfaAction } from "./enroll-action"

export default function MfaPage() {
  const [qr, setQr]           = useState<string | null>(null)
  const [secret, setSecret]   = useState<string | null>(null)
  const [factorId, setFactor] = useState<string | null>(null)
  const [code, setCode]       = useState("")
  const [status, setStatus]   = useState<"idle" | "enrolling" | "verifying" | "verified" | "error">("idle")
  const [error, setError]     = useState<string | null>(null)

  async function enroll() {
    setStatus("enrolling"); setError(null)
    try {
      const res = await enrollMfaAction()
      setQr(res.qr)
      setSecret(res.secret)
      setFactor(res.factorId)
      setStatus("idle")
    } catch (e) {
      setError(e instanceof Error ? e.message : "Enroll failed")
      setStatus("error")
    }
  }

  async function verify() {
    if (!factorId) return
    setStatus("verifying"); setError(null)
    const supabase = createClient()
    const { data: challenge } = await supabase.auth.mfa.challenge({ factorId })
    if (!challenge) { setError("Could not challenge factor"); setStatus("error"); return }
    const { error: verifyErr } = await supabase.auth.mfa.verify({
      factorId, challengeId: challenge.id, code,
    })
    if (verifyErr) { setError(verifyErr.message); setStatus("error"); return }
    setStatus("verified")
  }

  useEffect(() => { /* could auto-enroll on mount */ }, [])

  return (
    <div className="mx-auto max-w-md p-6 space-y-4">
      <h1 className="text-xl font-semibold">Two-factor authentication</h1>
      {!qr && (
        <button onClick={enroll} className="px-3 py-2 rounded bg-violet-600 text-white">
          {status === "enrolling" ? "Enrolling..." : "Enable TOTP"}
        </button>
      )}
      {qr && status !== "verified" && (
        <div className="space-y-3">
          <p className="text-sm">Scan with Authy / Google Authenticator / 1Password:</p>
          <img src={qr} alt="MFA QR" className="border" />
          <p className="text-xs text-zinc-500">Or enter the secret: <code className="font-mono">{secret}</code></p>
          <input
            value={code} onChange={(e) => setCode(e.target.value)}
            placeholder="6-digit code" maxLength={6}
            className="border rounded px-2 py-1 font-mono w-32"
          />
          <button onClick={verify} disabled={code.length !== 6} className="px-3 py-2 rounded bg-emerald-600 text-white disabled:opacity-50">
            {status === "verifying" ? "Verifying..." : "Verify"}
          </button>
        </div>
      )}
      {status === "verified" && <p className="text-emerald-600 font-semibold">✓ MFA enabled</p>}
      {error && <p className="text-red-600 text-sm">{error}</p>}
    </div>
  )
}
`
}

function buildMfaEnrollAction(): string {
  return `// Generated by SpringBloom — server action: enroll a TOTP factor.

"use server"

import { createServerClient } from "@/lib/auth/server"

export async function enrollMfaAction(): Promise<{ qr: string; secret: string; factorId: string }> {
  const supabase = await createServerClient()
  const { data, error } = await supabase.auth.mfa.enroll({
    factorType: "totp",
    friendlyName: "Authenticator",
  })
  if (error || !data) throw new Error(error?.message ?? "Enroll failed")
  return {
    qr:       data.totp.qr_code,
    secret:   data.totp.secret,
    factorId: data.id,
  }
}
`
}

function buildJwtHookSql(): string {
  return `-- Custom Access Token Hook — generated by SpringBloom.
--
-- Lets you inject custom claims into the JWT on every issuance / refresh.
-- Common uses: include user_role, plan, organization_id in the token so
-- your RLS policies can read them via auth.jwt().
--
-- Wire-up:
--   1. Apply this migration in your Supabase project.
--   2. Go to Authentication → Hooks → Custom Access Token → Enable
--      → Function: public.custom_access_token_hook
--   3. Test by signing in — verify the new claims appear in your JWT.
--
-- The hook receives the default event and returns a modified one.

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role text;
begin
  claims := event->'claims';

  -- Example: pull user_role from a profiles table
  -- select role into user_role from public.profiles where id = (event->>'user_id')::uuid;
  -- if user_role is not null then
  --   claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  -- end if;

  -- TODO: add your custom claims here.
  -- claims := jsonb_set(claims, '{plan}', to_jsonb('pro'));
  -- claims := jsonb_set(claims, '{org_id}', to_jsonb('xxx'));

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;

-- Allow Supabase Auth to call this function
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
grant all on table public.profiles to supabase_auth_admin;   -- needed if you read profiles
`
}
